### ISSUE TITLE
Array keys with dots not supported

### ISSUE THREAD

**Issue by llagerlof** [Hi-Folks/data-block#14]
Just doing some stress testing. I tried the code below, but don't work in that scenarios.

```php
<?php

require_once "./vendor/autoload.php";

use HiFolks\DataType\Block;

$arr = [
    'matrix' => [
        'main.actor' => 'Keanu Reeves',
        'imdb' => 8.7
    ],
    'independence_day' => [
        'main.actor' => 'Will Smith',
        'imdb' => 7
    ],
    'The.Abyss' => [
        'main.actor' => 'Ed Harris',
        'imdb' => 7.5
    ]
];

$movies = Block::make($arr);

$a = $movies->get('matrix.main.actor');

print_r($a);

$b = $movies->get('The.Abyss.imdb');

print_r($b);

$c = $movies->get('The.Abyss.main.actor'); 

print_r($c);
```

Maybe something like this could solve this issue? I don't know.

```php
$a = $movies->get('matrix."main.actor"');
```

**Comment by roberto-butti** [comment]
Hi @llagerlof thank you for testing the library.
To avoid conflict with the chars in the keys and the char used for determining the nested level, I introduced the `charNestedKey` parameter. By default, is a dot `.`, but you can change it in the case you need it.
I don't know if you already took a look at that parameter:

```php
$a = $movies->get(
    'matrix#main.actor',
    charNestedKey: '#'
);

```

Let me know if it can help.

**Comment by roberto-butti** [comment]
I'm going to close this issue because I think the `charNestedKey` is the solution.
If you have additional questions feel free to open new issues.


Thank you!
